spring:
  application:
    name:
      - spring-boot-app-info
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  info:
    java:
      enabled: true
    env:
      enabled: true

info:
  app:
    website: www.ravinder.com